nodeLinker: node-modules

npmScopes:
  multiverse-io:
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmPublishRegistry: 'https://npm.pkg.github.com'
