nodeLinker: node-modules

npmScopes:
  multiverse-io:
    npmRegistryServer: 'https://registry.npmjs.org'
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmAlwaysAuth: false
    npmAuthToken: "${NPM_TOKEN:-}"
